#!/bin/bash

function lint_file () {
    echo "Linting $1"
    # Get the type of the file and choose what to do.
    type=$(file --mime-type -b "$1")
    case $type in
        "text/x-shellscript")
            shellcheck "$1"
            ;;
        "text/x-python")
            isort -faas "$1"
            flake8 "$1"
            black -l 79 "$1"
            ;;
        *)
            echo "$1 was not processed"
    esac
}

for file in $(git diff --name-only --diff-filter=A develop)
do
    lint_file "$file"
done
